version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:15.0.1'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          command: maven/mvn -B -DskipTests clean package
  test:
    docker:
      - image: 'cimg/openjdk:15.0.1'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          command: maven/mvn test
  deliver:
    docker:
      - image: 'cimg/openjdk:15.0.1'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          command: ./jenkins/scripts/deliver.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deliver:
          requires:
            - test
