version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/base:2020.12'
    steps:
      - run:
          command: mvn -B -DskipTests clean package
  test:
    docker:
      - image: 'cimg/base:2020.12'
    steps:
      - run:
          command: mvn test
  deliver:
    docker:
      - image: 'cimg/base:2020.12'
    steps:
      - run:
          command: ./jenkins/scripts/deliver.sh
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deliver:
          requires:
            - test

