version: 2.1
orbs:
  maven: circleci/maven@1.0.3
jobs:
  build:
    steps:
      - checkout
      - run:
          command: mvn -B -DskipTests clean package
  test:
    steps:
      - run:
          command: mvn test
  deliver:
    steps:
      - run:
          command: ./jenkins/scripts/deliver.sh
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deliver:
          requires:
            - test

